# workflow 的名字
name: Build

# 触发 workflow 的事件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# 一个 workflow 由执行的一项或多项 job
jobs:
  # 一个 job 任务
  build:
    # 任务名为 building
    name: building
    # runs-on 指定 job 任务运行所需要的虚拟机环境
    runs-on: windows-latest
    
    # steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with: 
        arch: x86
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Run
      run: Release/GHAnalysis.exe
